### ISSUE TITLE
Where is this page hosted?

### ISSUE THREAD

**Issue by datawookie** [satRdays/amsterdam2018#2]
Hi,

I tried to find the page for this conference but Google was not being helpful. Perhaps you could put the URL for the web site into the README file?

Thanks, Andrew.

**Comment by RMHogervorst** [comment]
Great idea and thanks for the comment Andrew!

**Comment by datawookie** [comment]
No problem. Following up on this though. I'm keen to attend this meeting and I'd also like to submit a talk proposal. Can you please point me to the site? (Assuming that it is live alreay somewhere!).

**Comment by RMHogervorst** [comment]
Cool! The website is up but we have not arranged the submission yet.

**Comment by datawookie** [comment]
Great. Can you please share the URL with me? It doesn't seem to be well indexed on Google yet, so I am battling to find it.

**Comment by RMHogervorst** [comment]
Oh I'm so sorry, here is the link: http://amsterdam2018.satrdays.org/

**Comment by datawookie** [comment]
Great. Site looks good. Do you have a mailing list set up? Is it possible to get notified when the CfP opens?
